#!/bin/bash

#get_id_all_stacks

id_stacks=($(curl -s -u access_key:secret_key https://ip-rancher/v1/projects/1a5/environments | jq '.data[] | .id' | tr -d \"))

for var in $id_stacks
  do
    curl -s -u access_key:secret_key https://ip-rancher/v1/projects/1a5/environments | jq '.data[] | .id' | tr -d \" > ids_stacks
done


#get_name_all_stacks

id_stacks=($(curl -s -u access_key:secret_key https://ip-rancher/v1/projects/1a5/environments | jq '.data[] | .name' | tr -d \"))

for var in $id_stacks
  do
    curl -s -u access_key:secret_key https://ip-rancher/v1/projects/1a5/environments | jq '.data[] | .name' | tr -d \" > name_stacks
done


#create_directory_id_for_every_stack

file="ids_stacks"
for var in $(< $file)
  do
    mkdir $var
done

#create_directory_name_for_every_stack

file="name_stacks"
for var in $(< $file)
  do
    mkdir $var
done


#download_compose_archive_and_save_in_directory

file_id="ids_stacks"
for var in $(< $file_id)
  do
    curl -o $var.zip -s -u access_key:secret_key https://ip-rancher/v1/projects/1a5/environments/$var/composeconfig && mv $var.zip ./$var/ && cd ./$var/ && unzip $var.zip && rm $var.zip && cd ..
done


paste ids_stacks name_stacks > id-name-stack && awk '{print "mv "$0}' id-name-stack > id_name_stacks && chmod +x id_name_stacks && ./id_name_stacks && rm id-name-stack ids_stacks name_stacks id_name_stacks

